In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
anime=pd.read_csv("C:\\data science\\anime_Recomendation_dataset\\anime.csv")
ratings=pd.read_csv("C:\\data science\\anime_Recomendation_dataset\\rating.csv")

In [3]:
anime=anime.dropna()

In [4]:
ratings

         user_id  anime_id  rating
0              1        20      -1
1              1        24      -1
2              1        79      -1
3              1       226      -1
4              1       241      -1
...          ...       ...     ...
7813732    73515     16512       7
7813733    73515     17187       9
7813734    73515     22145      10
7813735    73516       790       9
7813736    73516      8074       9

[7813737 rows x 3 columns]

In [5]:
ratings=ratings.drop(ratings[ratings["rating"]==-1].index,axis=0)

In [6]:
anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [7]:
ratings_with_name=anime.merge(ratings,on="anime_id")

In [8]:
ratings_with_name

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,99,5
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,152,10
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,244,10
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,271,10
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,322,10
...,...,...,...,...,...,...,...,...,...
6337141,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211,58483,1
6337142,5543,Under World,Hentai,OVA,1,4.28,183,49503,4
6337143,5543,Under World,Hentai,OVA,1,4.28,183,58483,1
6337144,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219,49503,6
6337145,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,60365,4

In [9]:
x=ratings_with_name.groupby("user_id").count()["anime_id"].sort_values()>35
padhe_likhe_users=x[x].index
padhe_likhe_users

Int64Index([24257, 33370, 70845, 54269, 62906, 67716,  9462, 62871, 39652,
            52178,
            ...
            22434, 65840, 12431,  7345, 45659, 51693, 59643, 57620, 53698,
            42635],
           dtype='int64', name='user_id', length=38572)

In [10]:
## based on users
filtered_rating=ratings_with_name[ratings_with_name["user_id"].isin(padhe_likhe_users)]

In [11]:
filtered_rating

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,99,5
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,152,10
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,244,10
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,271,10
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,322,10
...,...,...,...,...,...,...,...,...,...
6337141,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211,58483,1
6337142,5543,Under World,Hentai,OVA,1,4.28,183,49503,4
6337143,5543,Under World,Hentai,OVA,1,4.28,183,58483,1
6337144,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219,49503,6
6337145,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,60365,4

In [36]:
y=filtered_rating.groupby("anime_id").count()["user_id"]>50
famous_animes=y[y].index

In [37]:
final_Ratings=filtered_rating[filtered_rating["anime_id"].isin(famous_animes)]

In [38]:
final_Ratings

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,99,5
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,152,10
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,244,10
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,271,10
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,322,10
...,...,...,...,...,...,...,...,...,...
6336792,1639,Boku no Pico,"Hentai, Yaoi",OVA,1,5.13,57355,73328,2
6336793,1639,Boku no Pico,"Hentai, Yaoi",OVA,1,5.13,57355,73329,6
6336794,1639,Boku no Pico,"Hentai, Yaoi",OVA,1,5.13,57355,73348,4
6336795,1639,Boku no Pico,"Hentai, Yaoi",OVA,1,5.13,57355,73389,7
6336796,1639,Boku no Pico,"Hentai, Yaoi",OVA,1,5.13,57355,73462,3

In [68]:
# pd.concat([pt_try,show_mode],axis=1)
final_Ratings["anime_id"].unique().shape

(5133,)

In [39]:
pt=final_Ratings.pivot_table(index="name",columns="user_id",values="rating_x")

In [40]:
pt.index[1000:]

Index(['Digimon Adventure Movie', 'Digimon Adventure tri. 1: Saikai',
       'Digimon Adventure tri. 2: Ketsui',
       'Digimon Adventure tri. 3: Kokuhaku',
       'Digimon Adventure: Bokura no War Game!', 'Digimon Frontier',
       'Digimon Frontier: Ornismon Fukkatsu!!', 'Digimon Savers',
       'Digimon Savers 3D: Digital World Kiki Ippatsu!',
       'Digimon Savers the Movie: Kyuukyoku Power! Burst Mode Hatsudou!!',
       ...
       'ef: A Tale of Memories.', 'ef: A Tale of Memories. - Prologue',
       'ef: A Tale of Memories. - Recollections', 'iDOLM@STER Xenoglossia',
       's.CRY.ed', 'xxxHOLiC', 'xxxHOLiC Kei',
       'xxxHOLiC Movie: Manatsu no Yoru no Yume', 'xxxHOLiC Rou',
       'xxxHOLiC Shunmuki'],
      dtype='object', name='name', length=4133)

In [41]:
pt.fillna(0,inplace=True)

In [42]:
pt_try.columns.shape[0]/3

12857.333333333334

In [43]:
from sklearn.metrics.pairwise import cosine_similarity
scores=cosine_similarity(pt)

In [59]:
pt.shape

(5133, 38572)

In [46]:
np.where(pt.index=="Boku no Pico")

(array([536], dtype=int64),)

In [45]:
def recommend(anime_name):
    index=np.where(pt.index==anime_name)[0][0]
    similar_items=sorted(list(enumerate(scores[index])),key=lambda x:x[1],reverse=True)[1:6]
    
    for i in similar_items:
        print(pt.index[i[0]])

In [65]:
recommend("Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou")
#recommend("Final Fantasy VII: On the Way to a Smile - Episode: Denzel")

Haikyuu!! Second Season
Haikyuu!!
Shokugeki no Souma: Ni no Sara
Kuroko no Basket 3rd Season
Boku no Hero Academia